# Dependencies and Imports

In [1]:
# !pip3 install torch pytorch-lightning

In [2]:
import os
import random
import torch
import torch.nn as nn
import torch.nn.functional as F # ReLU, Softmax
from torch.autograd import Variable
from torch.utils.data import Dataset, DataLoader, TensorDataset #, IterableDataset, TensorDataset
import torch.optim as optim
from sklearn.preprocessing import StandardScaler
import pytorch_lightning as pl
from pytorch_lightning import seed_everything
from pytorch_lightning.callbacks import LearningRateMonitor, EarlyStopping
from pytorch_lightning.tuner import Tuner
# from pytorch_lightning.callbacks import ModelCheckpoint
# from pytorch_lightning.loggers import TensorBoardLogger
# from pytorch_lightning.loggers import WandbLogger
# from pytorch_lightning.metrics import Accuracy, Precision, Recall, F1

from functools import reduce
import numpy as np
import pandas as pd
import datetime as dt
from dateutil.relativedelta import relativedelta
from datetime import date, timedelta

from NowcastingPipelineM import NowcastingPH_M
import dynamicfactoranalysis as dfa

# def set_seed(seed):
#     random.seed(seed)
#     np.random.seed(seed)
#     torch.manual_seed(seed)
#     torch.cuda.manual_seed(seed)
#     torch.cuda.manual_seed_all(seed)
#     # torch.backends.cudnn.deterministic = True                     # Only cuDNN convolution algorithms
#     torch.use_deterministic_algorithms(True)                        # All torch and cuDNN algorithms when available. RunTime error if not available.
#     torch.backends.cudnn.benchmark = False                          # Uses the same algorthim. May lose out on performance.
#     # torch.utils.deterministic.fill_uninitialized_memory = True    # For torch.empty() or torch.Tensor.resize()
#     os.environ['CUBLAS_WORKSPACE_CONFIG'] = ':16:8'                 # For RNN/LSTM
# seed_everything(42, workers=True)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)
print(torch.__version__)
print(torch.cuda.is_available())
print(torch.cuda.device_count())
print(torch.cuda.current_device())
print(torch.cuda.device(0))
print(torch.cuda.get_device_name(0))

cuda
2.6.0+cu124
True
1
0
<torch.cuda.device object at 0x7af1ee94abf0>
Quadro RTX 6000

# Dataset and Dataloader preparation

In [157]:
class NowcastingLSTM_MQ(NowcastingPH_M):
    def set_classname(self, **kwargs):
        self.prefix = f'LSTM{self.kwargs.get("lag_order")} x ' + ('DFM_Opt' if self.kwargs.get("optimize_order") else f'DFM{self.kwargs.get("DFM_order")}') if self.kwargs.get("extend") else f'LSTM{self.kwargs.get("lag_order")}'
    def load_tweets(self, vintage, window, kmpair, freq='M', extend=False, **kwargs):
        vintage = pd.to_datetime(vintage)
        tweets = pd.read_csv('data/PH_Tweets_v3.csv')
        tweets['date'] = pd.to_datetime(tweets['date']) + pd.offsets.MonthEnd(0)
        tweets = tweets.set_index('date')

        if len(kmpair) == 0:
            kmpair = {keyword: list(tweets.columns.drop('keyword')) for keyword in tweets['keyword'].unique()}
        data = [tweets[tweets['keyword'] == keyword][kmpair[keyword]].add_suffix(f'_{keyword}') for keyword in kmpair.keys()]
        tweets = reduce(lambda left, right: pd.merge(left, right, on='date', how='outer', sort=True), data)
        tweets = tweets.loc[dt.datetime(2010,1,1) : pd.to_datetime(vintage), :]
        # tweets = tweets.loc[pd.to_datetime(vintage)  - relativedelta(months =  (pd.to_datetime(vintage).month - 1)%3 + window) : pd.to_datetime(vintage), :]
        # tweets = super().load_tweets(vintage, freq='M', **kwargs)
        # DFM_order = self.kwargs.get('DFM_order')                                             ### temporary measure to solve stationarity error
        # kwargs['DFM_order'] = (1, DFM_order[1], DFM_order[2], DFM_order[3])                   ### temporary measure to solve stationarity error
        tweets = self.extend_data(tweets, vintage, **kwargs) if extend else tweets
        tweets.index = pd.PeriodIndex(tweets.index, freq=freq)
        return tweets
    def extend_data(self, df, vintage, DFM_order, optimize_order=False, **kwargs):
        ### Instead of extending until year end, just extend until current quarter end
        factor_order, error_order, k_factors, factor_lag = DFM_order
        # drop row if not enough non-missing (max safety)
        # df = df.dropna(thresh = k_factors * (1 + factor_lag))

        if optimize_order:
            model = dfa.DynamicFactorModelOptimizer(
                endog=df, k_factors_max=k_factors, factor_lag_max=factor_lag, factor_order_max=factor_order, 
                error_order_max=error_order, verbose=True,**kwargs).fit(**kwargs)
        else:
            model = dfa.DynamicFactorModel(
                endog=df, k_factors=k_factors, factor_lag=factor_lag, factor_order=factor_order, 
                error_order=error_order, **kwargs)
        results = model.fit(disp=False, maxiter=10, method='powell', ftol=1e-3, **kwargs)
        # results = model.fit(disp=False, maxiter=1000, method='powell', ftol=1e-5, **kwargs)
        
        df_extended = pd.DataFrame()
        for col in df.columns:
            col_extended = pd.concat([df[[col]].dropna(), 
                                    results.predict(start=df[col].dropna().index[-1], end=vintage + pd.offsets.QuarterEnd(0))[[col]].iloc[1:]])
            df_extended = pd.concat([df_extended, col_extended], axis=1)
        df_extended.index.name = df.index.name

        return df_extended

In [231]:
### Train & Backcast Data
vintage = pd.to_datetime('2017-01-31')
data_window = 12
kmpair = {'PE': ['CRVADER_BVN','CR_BxP_0'],'PU+': ['CRVADER_BVN','CR_BxP_0']} # kmpair = {'PE':['CR_B0']}
data_model = NowcastingLSTM_MQ(kmpair=kmpair, target='GDP')
train_data, target_scaler, econ_scaler, tweets_scaler = data_model.load_data(vintage=vintage,window=1000, kmpair=kmpair, with_econ=True, with_tweets=False, target_release_lag=True,scaled=True, extend=False, DFM_order=(1,0,1,0), optimize_order = False)
train_data = train_data.loc[pd.to_datetime('2010-01-31'):,:].dropna()
display(train_data)

backcast_vintage = vintage - relativedelta(months=1)
backcast_data, _, _, _ = data_model.load_data(vintage=backcast_vintage, window=1000, kmpair=kmpair, with_econ=True, with_tweets=False, target_release_lag=True,scaled=False, extend=True, DFM_order=(1,0,1,0), optimize_order = False)
backcast_data = backcast_data.loc[backcast_vintage + relativedelta(months = -((backcast_vintage.month - 1) % 3) - data_window, day=31):,:]#.dropna()#.reset_index()  # get first month of same qtr last year, but get final day. Based on window = 12
backcast_data.iloc[:,:1] = target_scaler.transform(backcast_data.iloc[:,:1])
backcast_data.iloc[:,1:] = econ_scaler.transform(backcast_data.iloc[:,1:10])
display(backcast_data)
# model.load_target(vintage=pd.to_datetime('2017-01-31'), target='GDP', growth=True, quarterly=True, freq='M', target_release_lag=False)

,target,ECN.pseiclose_YoY,ECN.tbill_usd90,ECN.phpusd_YoY,ECN.tdr_php360,ECN.govtexpt_YoY,ECN.m1_YoY,ECN.IPI_YoY,ECN.imports_YoY,ECN.exports_YoY
date,,,,,,,,,,
2010-01,1.352012,2.517938,-0.284098,-0.548772,1.223782,0.347837,0.451220,3.064697,1.600958,2.223921
2010-02,1.352012,2.561692,0.154962,-0.585722,1.301379,-0.520349,1.265573,2.685477,1.289299,2.224540
2010-03,1.352012,2.367615,0.418398,-1.198938,1.317140,1.784152,2.228285,1.909728,2.170977,2.313774
2010-04,1.240001,2.208546,0.418398,-1.584540,1.071013,0.910811,2.924937,2.504871,2.937054,1.365598
2010-05,1.240001,1.095018,0.418398,-0.874627,1.147397,1.320597,1.620550,1.983715,1.694440,1.903395
...,...,...,...,...,...,...,...,...,...,...
2016-05,0.827599,-1.158421,1.999014,1.003168,-0.690679,0.688719,-0.564785,-0.008880,2.692099,-0.540582
2016-06,0.827599,-0.847725,1.296518,0.664015,-0.740389,-1.466092,-0.357619,0.316361,0.851245,-1.025924
2016-07,0.743091,-0.709768,1.384330,0.803956,-0.825261,-0.660958,-0.258367,0.628280,-0.464733,-1.133776
2016-08,0.743091,-0.467543,1.911202,0.218995,-0.752514,-0.090556,0.414840,0.762093,0.403451,-0.562101
2016-09,0.743091,-0.411816,1.472142,0.278561,-0.819198,1.416951,-0.299419,0.545319,0.553385,0.061368

/home/btiu/Documents/Research/TweetsNowcast/.venv/lib/python3.10/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
/home/btiu/Documents/Research/TweetsNowcast/.venv/lib/python3.10/site-packages/statsmodels/tsa/statespace/representation.py:374: FutureWarning: Unknown keyword arguments: dict_keys(['kmpair', 'with_econ', 'with_tweets', 'target_release_lag']).Passing unknown keyword arguments will raise a TypeError beginning in version 0.15.
  warnings.warn(msg, FutureWarning)
/home/btiu/Documents/Research/TweetsNowcast/.venv/lib/python3.10/site-packages/statsmodels/base/optimizer.py:19: FutureWarning: Keyword arguments have been passed to the optimizer that have no effect. The list of allowed keyword arguments for method powell is: xtol, ftol, maxfun, start_direc. The list of unsupported keyword arguments passed include: with_tweets, with_econ, kmpair, target_release_lag. After release 0.14, this will raise.
  warnings.warn(

,target,ECN.pseiclose_YoY,ECN.tbill_usd90,ECN.phpusd_YoY,ECN.tdr_php360,ECN.govtexpt_YoY,ECN.m1_YoY,ECN.IPI_YoY,ECN.imports_YoY,ECN.exports_YoY
date,,,,,,,,,,
2015-10,0.523853,-1.087929,-0.284098,0.705006,-0.746451,0.714846,-1.016972,-1.092726,0.469834,-1.131943
2015-11,0.523853,-1.311733,0.945270,0.931831,-0.573071,-0.087083,-1.073032,-0.761784,-0.047284,-0.518795
2015-12,0.523853,-1.243903,0.418398,1.165762,-0.386353,-0.500019,-1.235353,-0.743178,0.262764,-0.636538
2016-01,0.426368,-1.769963,1.823390,1.338958,-0.620356,-0.673741,-1.543056,-0.248293,0.744833,-0.595717
2016-02,0.426368,-1.808455,1.911202,1.591316,-0.590045,0.288191,-1.443924,0.596098,-0.922067,-0.660685
2016-03,0.426368,-1.512559,0.857458,1.047783,-0.546397,0.602895,-0.157781,-0.043148,0.503029,-1.265490
2016-04,0.827599,-1.435784,0.945270,0.856488,-0.668854,0.625993,-0.613475,0.277751,1.907230,-0.661165
2016-05,0.827599,-1.158421,1.999014,1.003168,-0.690679,0.688719,-0.564785,-0.008880,2.692099,-0.540582
2016-06,0.827599,-0.847725,1.296518,0.664015,-0.740389,-1.466092,-0.357619,0.316361,0.851245,-1.025924
2016-07,0.743091,-0.709768,1.384330,0.803956,-0.825261,-0.660958,-0.258367,0.628280,-0.464733,-1.133776
2016-08,0.743091,-0.467543,1.911202,0.218995,-0.752514,-0.090556,0.414840,0.762093,0.403451,-0.562101
2016-09,0.743091,-0.411816,1.472142,0.278561,-0.819198,1.416951,-0.299419,0.545319,0.553385,0.061368
2016-10,NaN,-0.805990,1.999014,0.872012,-0.739177,-1.556527,-0.305628,0.402307,0.030415,0.162495
2016-11,NaN,-1.143887,3.228382,0.931398,-0.634906,1.393502,-1.039473,-0.289746,-0.280503,-0.124227
2016-12,NaN,-1.115080,3.404006,1.120606,-0.640681,-0.185826,-1.089427,-0.255176,-0.249085,-0.105028

In [226]:
def sliding_windows(data_x, seq_length, freq_ratio = 3):
    '''
    seq_length = number of rows of historical data + number of rows of input data (i.e. 12 + 3)
    '''
    x_encoder_in = []
    y_decoder_in = []
    y_target = []

    for i in range(0,len(data_x)-seq_length+1, freq_ratio):
        _x_in = data_x.iloc[i:(i+seq_length),1:]
        _y_in = data_x.iloc[i+freq_ratio-1:i+seq_length-freq_ratio:freq_ratio, :1] # gets every rth row but stops before the current low-freq vintage
        _y_out = data_x.iloc[i+seq_length-1, :1]
        x_encoder_in.append(_x_in)
        y_decoder_in.append(_y_in)
        y_target.append(_y_out)
    
    return np.array(x_encoder_in),np.array(y_decoder_in), np.array(y_target)
x_encoder_in, y_decoder_in, y_target = sliding_windows(train_data, seq_length=15)
print(x_encoder_in.shape) # (timesteps, seq_length, dim_x)
print(y_decoder_in.shape) # (timesteps, dim_y)
print(y_target.shape)
trainX_in = Variable(torch.Tensor(x_encoder_in)).to(device)
trainY_in = Variable(torch.Tensor(y_decoder_in)).to(device)
trainY_out = Variable(torch.Tensor(y_target)).to(device)

x_encoder_backcast_in, y_decoder_backcast_in, _ = sliding_windows(backcast_data, seq_length=15)
backcastX_in = Variable(torch.Tensor(x_encoder_backcast_in)).to(device)
backcastY_in = Variable(torch.Tensor(y_decoder_backcast_in)).to(device)

(23, 15, 9)
(23, 4, 1)
(23, 1)

# Model Definition

In [206]:
### seq2seq y
class PreAttnEncoder(nn.Module):
    def __init__(self, dim_x, n_a, dropout_rate=0.2, bidirectional_encoder=False):
        super(PreAttnEncoder, self).__init__()
        self.bidirectional_encoder = bidirectional_encoder
        self.lstm = nn.LSTM(dim_x, n_a, batch_first=True, bidirectional=bidirectional_encoder)
        self.dropout = nn.Dropout(dropout_rate)

    def forward(self, x):
        a, _ = self.lstm(x)
        return a

class OneStepAttn(nn.Module):
    def __init__(self, n_a, n_s, n_align):
        super(OneStepAttn, self).__init__()
        self.densor1 = nn.Linear(n_a + n_s, n_align)
        self.densor2 = nn.Linear(n_align, 1)

    def forward(self, a, s_prev):
        s_prev = s_prev.unsqueeze(1).repeat(1, a.size(1), 1) # (batch_size, Lx, n_s)
        concat = torch.cat((a, s_prev), dim=-1) # (batch_size, Lx, n_a + n_s)
        e = torch.tanh(self.densor1(concat))
        energies = F.relu(self.densor2(e))  # (batch_size, Lx, 1)
        alphas = F.softmax(energies, dim=1) # (batch_size, Lx, 1)
        context = torch.bmm(alphas.transpose(1, 2), a).squeeze(1) # (batch_size, n_a)
        return context

class MTMFSeq2Seq(nn.Module):
    def __init__(self, dim_x, dim_y, Lx, Ty, n_a, n_s, n_align_y, fc_y, dropout_rate, freq_ratio=3, bidirectional_encoder=False, l1reg=1e-5, l2reg=1e-4):
        super(MTMFSeq2Seq, self).__init__()
        self.dim_x = dim_x
        self.dim_y = dim_y
        self.Lx = Lx
        self.Ty = Ty
        self.n_a = n_a
        self.n_s = n_s
        self.n_align_y = n_align_y
        self.fc_y = fc_y
        self.freq_ratio = freq_ratio
        self.bidirectional_encoder = bidirectional_encoder
        self.l1reg = l1reg
        self.l2reg = l2reg

        self.pre_attn = PreAttnEncoder(dim_x, n_a, dropout_rate, bidirectional_encoder)
        self.one_step_attention_y = OneStepAttn(n_a, n_s, n_align_y)

        self.post_attn_y = nn.LSTMCell(n_a + dim_y, n_s)
        self.ffn1_y = nn.Linear(n_s, fc_y)
        self.dropout_fn_y = nn.Dropout(dropout_rate)
        self.ffn2_y = nn.Linear(fc_y, dim_y) ### add regularizer

    def initialize_state(self, batch_size, dim, device):
        return torch.zeros(batch_size, dim, device=device)

    def forward(self, x_encoder_in, y_decoder_in):
        batch_size = x_encoder_in.size(0)

        a = self.pre_attn(x_encoder_in)

        s_y, c_y = self.initialize_state(batch_size, self.n_s, device), self.initialize_state(batch_size, self.n_s, device)
        for t in range(self.Ty):
            a_idx = int((t + 1) * self.freq_ratio - 1)
            a_to_attend = a[:, (a_idx - self.freq_ratio + 1):(a_idx + 1), :]
            context = self.one_step_attention_y(a_to_attend, s_y)
            post_attn_input = torch.cat((context, y_decoder_in[:, t, :]), dim=-1)
            s_y, c_y = self.post_attn_y(post_attn_input, (s_y, c_y))

        y_pred = F.relu(self.ffn1_y(s_y))
        y_pred = self.dropout_fn_y(y_pred)
        y_pred = self.ffn2_y(y_pred)

        return y_pred

In [ ]:
seed_everything(42, workers=True)

class MTMFSeq2SeqLightning(pl.LightningModule):
    def __init__(self, model, learning_rate=0.0001):
        super(MTMFSeq2SeqLightning, self).__init__()
        self.model = model
        self.learning_rate = learning_rate
        self.criterion = torch.nn.MSELoss()

    def forward(self, x_encoder_in, y_decoder_in):
        return self.model(x_encoder_in, y_decoder_in)

    def training_step(self, batch, batch_idx):
        x_encoder_in, y_decoder_in, y_target = batch
        y_pred = self(x_encoder_in, y_decoder_in)
        loss = self.criterion(y_pred, y_target)
        self.log("train_loss", loss, prog_bar=True)
        return loss

    def configure_optimizers(self):
        return optim.Adam(self.parameters(), lr=self.learning_rate)

# Prepare the dataset and dataloader
train_dataset = TensorDataset(trainX_in, trainY_in, trainY_out)
train_loader = DataLoader(train_dataset, batch_size=24, shuffle=True, num_workers=8)

# Initialize the model
dim_x = trainX_in.shape[-1] # 9
dim_y = trainY_in.shape[-1] # 1
Lx = trainX_in.shape[1] # 15
Ty = trainY_in.shape[1] # 4
n_a = 128
n_s = 256
n_align_y = 16
fc_y = 128
dropout_rate = 0.4
freq_ratio = 3
bidirectional_encoder = False

model = MTMFSeq2Seq(
    dim_x=dim_x,
    dim_y=dim_y,
    Lx=Lx,
    Ty=Ty,
    n_a=n_a,
    n_s=n_s,
    n_align_y=n_align_y,
    fc_y=fc_y,
    dropout_rate=dropout_rate,
    freq_ratio=freq_ratio,
    bidirectional_encoder=bidirectional_encoder,
)

# Initialize the Lightning module
lightning_model = MTMFSeq2SeqLightning(model).to(device)
lr_monitor = LearningRateMonitor(logging_interval='step')

# Find learning rate and train model with new learning rate
trainer = pl.Trainer(max_epochs=200, accelerator='auto',log_every_n_steps=1, callbacks=[lr_monitor], deterministic=True)
tuner = Tuner(trainer)
lr_finder = tuner.lr_find(lightning_model, train_loader)
lightning_model.hparams.lr = lr_finder.suggestion()
trainer.fit(lightning_model, train_loader)

Seed set to 42
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
Finding best initial lr:  90%|█████████ | 90/100 [00:29<00:03,  3.07it/s]
LR finder stopped early after 90 steps due to diverging loss.
Learning rate set to 0.001584893192461114
Restoring states from the checkpoint path at /home/btiu/Documents/Research/TweetsNowcast/.lr_find_ccd85f4a-036b-4d9f-9472-1effd22c4004.ckpt
Restored all states from the checkpoint at /home/btiu/Documents/Research/TweetsNowcast/.lr_find_ccd85f4a-036b-4d9f-9472-1effd22c4004.ckpt
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name      | Type        | Params | Mode
--------------------------------------------------
0 | model     | MTMFSeq2Seq | 506 K  | train
1 | criterion | MSELoss     | 0      | train
--------------------------------------------------
506 K     Trainable params
0         Non-trainable params
506 K     Total params
2.027     Total estimated model params size (MB)
12        Modules in train mode
0         Modules in eval mode

Epoch 199: 100%|██████████| 1/1 [00:00<00:00,  3.00it/s, v_num=0, train_loss=0.0135]

`Trainer.fit` stopped: `max_epochs=200` reached.

Epoch 199: 100%|██████████| 1/1 [00:00<00:00,  2.70it/s, v_num=0, train_loss=0.0135]

In [246]:
# Set the model to evaluation mode
lightning_model.eval()
# Perform inference on backcast data
with torch.no_grad():
    backcasts = lightning_model(torch.Tensor(x_encoder_backcast_in).to(device), torch.Tensor(y_decoder_backcast_in).to(device))
backcasts_np = backcasts.cpu().numpy()
backcasts_inverse = target_scaler.inverse_transform(backcasts_np)

# Display the backcasts
print("Backcasts (scaled):", backcasts_np)
print("Backcasts (original scale):", backcasts_inverse)

Backcasts (scaled): [[0.611628]]
Backcasts (original scale): [[7.1591253]]

In [ ]:
test_data, _, _, _ = data_model.load_data(vintage=vintage, window=1000, kmpair=kmpair, with_econ=True, with_tweets=False, target_release_lag=True,scaled=False, extend=True, DFM_order=(1,0,1,0), optimize_order = False)
test_data = test_data.loc[vintage + relativedelta(months = -((vintage.month - 1) % 3) - data_window, day=31):,:]#.dropna()#.reset_index()  # get first month of same qtr last year, but get final day. Based on window = 12
test_data.iloc[:,:1] = target_scaler.transform(test_data.iloc[:,:1])
test_data.iloc[:,1:] = econ_scaler.transform(test_data.iloc[:,1:10])
display(test_data)
x_encoder_test_in, y_decoder_test_in, _ = sliding_windows(test_data, seq_length=15)
y_decoder_test_in[:, -1, :] = backcasts_np

/home/btiu/Documents/Research/TweetsNowcast/.venv/lib/python3.10/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency ME will be used.
  self._init_dates(dates, freq)
/home/btiu/Documents/Research/TweetsNowcast/.venv/lib/python3.10/site-packages/statsmodels/tsa/statespace/representation.py:374: FutureWarning: Unknown keyword arguments: dict_keys(['kmpair', 'with_econ', 'with_tweets', 'target_release_lag']).Passing unknown keyword arguments will raise a TypeError beginning in version 0.15.
  warnings.warn(msg, FutureWarning)
/home/btiu/Documents/Research/TweetsNowcast/.venv/lib/python3.10/site-packages/statsmodels/base/optimizer.py:19: FutureWarning: Keyword arguments have been passed to the optimizer that have no effect. The list of allowed keyword arguments for method powell is: xtol, ftol, maxfun, start_direc. The list of unsupported keyword arguments passed include: with_tweets, with_econ, kmpair, target_release_lag. After release 0.14, this will raise.
  warnings.warn(

,target,ECN.pseiclose_YoY,ECN.tbill_usd90,ECN.phpusd_YoY,ECN.tdr_php360,ECN.govtexpt_YoY,ECN.m1_YoY,ECN.IPI_YoY,ECN.imports_YoY,ECN.exports_YoY
date,,,,,,,,,,
2016-01,0.426368,-1.769963,1.823390,1.338958,-0.620356,-0.673741,-1.543056,-0.248293,0.744833,-0.595717
2016-02,0.426368,-1.808455,1.911202,1.591316,-0.590045,0.288191,-1.443924,0.596098,-0.922067,-0.660685
2016-03,0.426368,-1.512559,0.857458,1.047783,-0.546397,0.602895,-0.157781,-0.043148,0.503029,-1.265490
2016-04,0.827599,-1.435784,0.945270,0.856488,-0.668854,0.625993,-0.613475,0.277751,1.907230,-0.661165
2016-05,0.827599,-1.158421,1.999014,1.003168,-0.690679,0.688719,-0.564785,-0.008880,2.692099,-0.540582
2016-06,0.827599,-0.847725,1.296518,0.664015,-0.740389,-1.466092,-0.357619,0.316361,0.851245,-1.025924
2016-07,0.743091,-0.709768,1.384330,0.803956,-0.825261,-0.660958,-0.258367,0.628280,-0.464733,-1.133776
2016-08,0.743091,-0.467543,1.911202,0.218995,-0.752514,-0.090556,0.414840,0.762093,0.403451,-0.562101
2016-09,0.743091,-0.411816,1.472142,0.278561,-0.819198,1.416951,-0.299419,0.545319,0.553385,0.061368
2016-10,NaN,-0.805990,1.999014,0.872012,-0.739177,-1.556527,-0.305628,0.402307,0.030415,0.162495
2016-11,NaN,-1.143887,3.228382,0.931398,-0.634906,1.393502,-1.039473,1.156271,0.784309,-0.733466
2016-12,NaN,-1.115080,3.404006,1.120606,-0.512448,0.251443,-1.233288,-0.245697,-0.242728,-0.106978
2017-01,NaN,-0.558895,3.579630,0.955129,-0.519676,-0.147838,-0.962643,-0.204809,-0.205715,-0.084738
2017-02,NaN,-0.135441,-0.304009,-0.231433,-0.491760,-0.139677,-0.931912,-0.195383,-0.197182,-0.079611
2017-03,NaN,-0.137985,-0.305964,-0.230843,-0.497526,-0.141362,-0.938260,-0.197330,-0.198945,-0.080670

In [244]:
# Set the model to evaluation mode
lightning_model.eval()
# Perform inference on backcast data
with torch.no_grad():
    predictions = lightning_model(torch.Tensor(x_encoder_test_in).to(device), torch.Tensor(y_decoder_test_in).to(device))
predictions_np = predictions.cpu().numpy()
predictions_inverse = target_scaler.inverse_transform(predictions_np)

# Display the predictions
print("Predictions (scaled):", predictions_np)
print("Predictions (original scale):", predictions_inverse)

Predictions (scaled): [[0.29147112]]
Predictions (original scale): [[6.743473]]

In [ ]:
# # trainer.checkpoint_callback.last_model_path
# trainer = pl.Trainer(
#     max_epochs=200,
#     accelerator='auto',
#     log_every_n_steps=1,
# )
# trainer.fit(lightning_model, train_loader, ckpt_path = 'lightning_logs/version_50/checkpoints/epoch=99-step=100.ckpt')

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
Restoring states from the checkpoint path at lightning_logs/version_50/checkpoints/epoch=99-step=100.ckpt
/home/btiu/Documents/Research/TweetsNowcast/.venv/lib/python3.10/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:362: The dirpath has changed from '/home/btiu/Documents/Research/TweetsNowcast/lightning_logs/version_50/checkpoints' to '/home/btiu/Documents/Research/TweetsNowcast/lightning_logs/version_52/checkpoints', therefore `best_model_score`, `kth_best_model_path`, `kth_value`, `last_model_path` and `best_k_models` won't be reloaded. Only `best_model_path` will be reloaded.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name      | Type        | Params | Mode
--------------------------------------------------
0 | model     | MTMFSeq2Seq | 506 K  | train
1 | criterion | MSELoss     | 0      | train
--------------------------------------------------
506 K     Trainable params
0         Non-trainable params
506 K     Total params
2.027     Total estimated model params size (MB)
12        Modules in train mode
0         Modules in eval mode
Restored all states from the checkpoint at lightning_logs/version_50/checkpoints/epoch=99-step=100.ckpt

Epoch 199: 100%|██████████| 1/1 [00:00<00:00,  3.08it/s, v_num=52, train_loss=0.0303]

`Trainer.fit` stopped: `max_epochs=200` reached.

Epoch 199: 100%|██████████| 1/1 [00:00<00:00,  2.74it/s, v_num=52, train_loss=0.0303]

In [11]:
%reload_ext tensorboard
%tensorboard --logdir=lightning_logs/

Reusing TensorBoard on port 6006 (pid 771975), started 0:12:17 ago. (Use '!kill 771975' to kill it.)

In [ ]:
# ### seq2one y
# class PreAttnEncoder(nn.Module):
#     """Pre-attention Encoder module"""
#     def __init__(self, dim_x, n_a, dropout_rate=0.2, bidirectional_encoder=False):
#         super(PreAttnEncoder, self).__init__()
#         self.bidirectional_encoder = bidirectional_encoder
#         self.lstm = nn.LSTM( input_size=dim_x, hidden_size=n_a, batch_first=True, bidirectional=bidirectional_encoder)
#         self.dropout = nn.Dropout(dropout_rate)

#     def forward(self, x):
#         a, _ = self.lstm(x)
#         return a


# class OneStepAttn(nn.Module):
#     """Attention alignment module"""
#     def __init__(self, n_a, n_s, n_align):
#         super(OneStepAttn, self).__init__()
#         self.densor1 = nn.Linear(n_a + n_s, n_align)
#         self.densor2 = nn.Linear(n_align, 1)

#     def forward(self, a, s_prev):
#         s_prev = s_prev.unsqueeze(1).repeat(1, a.size(1), 1)
#         concat = torch.cat((a, s_prev), dim=-1)
#         e = torch.tanh(self.densor1(concat))
#         energies = F.relu(self.densor2(e))
#         alphas = F.softmax(energies, dim=1)
#         context = torch.sum(alphas * a, dim=1)
#         return context


# class MTMFSeq2One(nn.Module):
#     def __init__(
#         self,
#         Lx,
#         dim_x,
#         Ty,
#         dim_y,
#         n_a,
#         n_s,
#         n_align,
#         fc_y,
#         dropout_rate,
#         freq_ratio=3,
#         bidirectional_encoder=False
#     ):
#         super(MTMFSeq2One, self).__init__()
#         self.Lx = Lx
#         self.Ty = Ty
#         self.dim_x = dim_x
#         self.dim_y = dim_y
#         self.n_a = n_a
#         self.n_s = n_s
#         self.n_align = n_align
#         self.fc_y = fc_y
#         self.freq_ratio = freq_ratio
#         self.bidirectional_encoder = bidirectional_encoder

#         # Encoder
#         self.pre_attn = PreAttnEncoder(dim_x, n_a, dropout_rate, bidirectional_encoder)

#         # Attention alignment model
#         self.one_step_attention = OneStepAttn(n_a, n_s, n_align)

#         # Decoder
#         self.post_attn = nn.LSTMCell(input_size=n_a + dim_y, hidden_size=n_s)
#         self.ffn1 = nn.Linear(n_s, fc_y)
#         self.dropout = nn.Dropout(dropout_rate)
#         self.ffn2 = nn.Linear(fc_y, dim_y) ### add regularizer

#     def initialize_state(self, batch_size, dim, device):
#         return torch.zeros(batch_size, dim, device=device)

#     def forward(self, batch_inputs):
#         x, y = batch_inputs
#         batch_size = x.size(0)

#         # Stage 1: Pre-attention encoding
#         a = self.pre_attn(x)

#         # Stage 2: Attention-based decoding
#         s = self.initialize_state(batch_size, self.n_s, device)
#         c = self.initialize_state(batch_size, self.n_s, device)

#         for t in range(self.Ty):
#             a_idx = int((t + 1) * self.freq_ratio - 1)
#             a_to_attend = a[:, (a_idx - self.freq_ratio + 1):(a_idx + 1), :]
#             context = self.one_step_attention(a_to_attend, s)

#             post_attn_input = torch.cat((context, y[:, t, :].unsqueeze(1)), dim=-1)
#             s, c = self.post_attn(post_attn_input.squeeze(1), (s, c))

#         y_pred = F.relu(self.ffn1(s))
#         y_pred = self.dropout(y_pred)
#         y_pred = self.ffn2(y_pred)

#         return y_pred

In [ ]:
# ### seq2one x, y

# class PreAttnEncoder(nn.Module):
#     """Pre-attention Encoder module"""
#     def __init__(self, dim_x, fc_dim, n_a, dropout_rate=0.2, bidirectional_encoder=False, l1reg=1e-5, l2reg=1e-4):
#         super(PreAttnEncoder, self).__init__()
#         self.bidirectional_encoder = bidirectional_encoder
#         self.l1reg = l1reg
#         self.l2reg = l2reg

#         self.lstm = nn.LSTM(input_size=dim_x, hidden_size=n_a, batch_first=True, bidirectional=bidirectional_encoder)
#         self.ffn1 = nn.Linear(n_a * (2 if bidirectional_encoder else 1), fc_dim)
#         self.dropout = nn.Dropout(dropout_rate)
#         self.ffn2 = nn.Linear(fc_dim, dim_x) ### add regularizer

#     def forward(self, x):
#         """
#         Forward pass for the encoder
#         Args:
#             x: (tensor) shape (batch_size, Lx, dim_x)
#         Returns:
#             x_pred: (tensor), the next step prediction for x (batch_size, dim_x)
#             a: (tensor) sequence of LSTM hidden states, (batch_size, Lx, n_a)
#         """
#         a, _ = self.lstm(x)
#         x_pred = F.relu(self.ffn1(a[:, -1, :]))
#         x_pred = self.dropout(x_pred)
#         x_pred = self.ffn2(x_pred)
#         return x_pred, a


# class OneStepAttn(nn.Module):
#     """Attention alignment module"""
#     def __init__(self, n_a, n_s, n_align):
#         super(OneStepAttn, self).__init__()
#         self.densor1 = nn.Linear(n_a + n_s, n_align)
#         self.densor2 = nn.Linear(n_align, 1)

#     def forward(self, a, s_prev):
#         """
#         Performs one step of attention
#         Args:
#             a: hidden state from the pre-attention LSTM, shape = (batch_size, Lx, n_a)
#             s_prev: previous hidden state of the post-attention LSTM, shape = (batch_size, n_s)
#         Returns:
#             context: context vector, input of the next post-attention LSTM cell
#         """
#         s_prev = s_prev.unsqueeze(1).repeat(1, a.size(1), 1)  # (batch_size, Lx, n_s)
#         concat = torch.cat((a, s_prev), dim=-1)  # (batch_size, Lx, n_a + n_s)
#         e = torch.tanh(self.densor1(concat))
#         energies = F.relu(self.densor2(e))  # (batch_size, Lx, 1)
#         alphas = F.softmax(energies, dim=1)  # (batch_size, Lx, 1)
#         context = torch.bmm(alphas.transpose(1,2), a).squeeze(1)  # (batch_size, n_a)
#         return context


# class MTMFSeq2One(nn.Module):
#     def __init__( self, Lx, dim_x, Ty, dim_y, n_a, n_s, n_align, fc_x, fc_y, dropout_rate, freq_ratio=3, bidirectional_encoder=False, l1reg=1e-5, l2reg=1e-4):
#         super(MTMFSeq2One, self).__init__()
#         self.dim_x = dim_x
#         self.dim_y = dim_y
#         self.Lx = Lx
#         self.Ty = Ty
#         self.n_a = n_a
#         self.n_s = n_s
#         self.n_align = n_align
#         self.fc_x = fc_x
#         self.fc_y = fc_y
#         self.freq_ratio = freq_ratio
#         self.bidirectional_encoder = bidirectional_encoder
#         self.l1reg = l1reg
#         self.l2reg = l2reg

#         # Encoder
#         self.pre_attn = PreAttnEncoder(dim_x, fc_x, n_a, dropout_rate, bidirectional_encoder, l1reg, l2reg)
#         # Attention alignment model
#         self.one_step_attention = OneStepAttn(n_a, n_s, n_align)
#         # Decoder
#         self.post_attn = nn.LSTMCell(n_a + dim_y, n_s)
#         self.ffn1 = nn.Linear(n_s, fc_y)
#         self.dropout = nn.Dropout(dropout_rate)
#         self.ffn2 = nn.Linear(fc_y, dim_y) ### add regularizer

#     def initialize_state(self, batch_size, dim, device):
#         return torch.zeros(batch_size, dim, device=device)

#     def forward(self, batch_inputs):
#         """
#         Forward pass
#         Args:
#             batch_inputs: tuple of (x, y) where
#                 x: encoder input, shape (batch_size, Lx, dim_x)
#                 y: decoder input, shape (batch_size, Ty, dim_y)
#         Returns:
#             x_pred: prediction for x
#             y_pred: prediction for y
#         """
#         x, y = batch_inputs
#         batch_size = x.size(0)

#         # Stage 1: Pre-attention encoding
#         x_pred, a = self.pre_attn(x)

#         # Stage 2: Attention-based decoding
#         s = self.initialize_state(batch_size, self.n_s, device)
#         c = self.initialize_state(batch_size, self.n_s, device)
#         for t in range(self.Ty):
#             a_idx = int((t + 1) * self.freq_ratio - 1)
#             a_to_attend = a[:, (a_idx - self.freq_ratio + 1):(a_idx + 1), :]
#             context = self.one_step_attention(a_to_attend, s)
#             post_attn_input = torch.cat((context, y[:, t, :]), dim=-1)
#             s, c = self.post_attn(post_attn_input, (s, c))

#         y_pred = F.relu(self.ffn1(s))
#         y_pred = self.dropout(y_pred)
#         y_pred = self.ffn2(y_pred)
#         return x_pred, y_pred

In [ ]:
# ### seq2seq y
# class PreAttnEncoder(nn.Module):
#     def __init__(self, dim_x, n_a, dropout_rate=0.2, bidirectional_encoder=False):
#         super(PreAttnEncoder, self).__init__()
#         self.bidirectional_encoder = bidirectional_encoder
#         self.lstm = nn.LSTM(dim_x, n_a, batch_first=True, bidirectional=bidirectional_encoder)
#         self.dropout = nn.Dropout(dropout_rate)

#     def forward(self, x):
#         a, _ = self.lstm(x)
#         return a

# class OneStepAttn(nn.Module):
#     def __init__(self, n_a, n_s, n_align):
#         super(OneStepAttn, self).__init__()
#         self.densor1 = nn.Linear(n_a + n_s, n_align)
#         self.densor2 = nn.Linear(n_align, 1)

#     def forward(self, a, s_prev):
#         s_prev = s_prev.unsqueeze(1).repeat(1, a.size(1), 1) # (batch_size, Lx, n_s)
#         concat = torch.cat((a, s_prev), dim=-1) # (batch_size, Lx, n_a + n_s)
#         e = torch.tanh(self.densor1(concat))
#         energies = F.relu(self.densor2(e))  # (batch_size, Lx, 1)
#         alphas = F.softmax(energies, dim=1) # (batch_size, Lx, 1)
#         context = torch.bmm(alphas.transpose(1, 2), a).squeeze(1) # (batch_size, n_a)
#         return context

# class MTMFSeq2Seq(nn.Module):
#     def __init__(self, dim_x, dim_y, Lx, Ty, n_a, n_s, n_align_y, fc_y, dropout_rate, freq_ratio=3, bidirectional_encoder=False, l1reg=1e-5, l2reg=1e-4):
#         super(MTMFSeq2Seq, self).__init__()
#         self.dim_x = dim_x
#         self.dim_y = dim_y
#         self.Lx = Lx
#         self.Ty = Ty
#         self.n_a = n_a
#         self.n_s = n_s
#         self.n_align_y = n_align_y
#         self.fc_y = fc_y
#         self.freq_ratio = freq_ratio
#         self.bidirectional_encoder = bidirectional_encoder
#         self.l1reg = l1reg
#         self.l2reg = l2reg

#         self.pre_attn = PreAttnEncoder(dim_x, n_a, dropout_rate, bidirectional_encoder)
#         self.one_step_attention_y = OneStepAttn(n_a, n_s, n_align_y)

#         self.post_attn_y = nn.LSTMCell(n_a + dim_y, n_s)
#         self.ffn1_y = nn.Linear(n_s, fc_y)
#         self.dropout_fn_y = nn.Dropout(dropout_rate)
#         self.ffn2_y = nn.Linear(fc_y, dim_y) ### add regularizer

#     def initialize_state(self, batch_size, dim, device):
#         return torch.zeros(batch_size, dim, device=device)

#     def forward(self, x_encoder_in, y_decoder_in):
#         batch_size = x_encoder_in.size(0)

#         a = self.pre_attn(x_encoder_in)

#         s_y, c_y = self.initialize_state(batch_size, self.n_s, device), self.initialize_state(batch_size, self.n_s, device)
#         for t in range(self.Ty):
#             a_idx = int((t + 1) * self.freq_ratio - 1)
#             a_to_attend = a[:, (a_idx - self.freq_ratio + 1):(a_idx + 1), :]
#             context = self.one_step_attention_y(a_to_attend, s_y)
#             post_attn_input = torch.cat((context, y_decoder_in[:, t, :]), dim=-1)
#             s_y, c_y = self.post_attn_y(post_attn_input, (s_y, c_y))

#         y_pred = F.relu(self.ffn1_y(s_y))
#         y_pred = self.dropout_fn_y(y_pred)
#         y_pred = self.ffn2_y(y_pred)

#         return y_pred